### ISSUE TITLE
tracking bad

### ISSUE THREAD

**Issue by sys-256** [shruuub/umami#1]
😃

**Comment by shruuub** [comment]
Says the guy how used tracking on sys-256.cock 🙂

**Comment by shruuub** [comment]
*who fuck

**Comment by sys-256** [comment]
ono 🙂

https://github.com/sys-256/sys-256.me/commit/031ec10bb041d123630b6aec6e8912512c594c3f
sir i removed it on january fifth :smile:

**Comment by sys-256** [comment]
why was that comit so hard to find

iot litearly took me  6mintues

**Comment by shruuub** [comment]
> why was that comit so hard to find
> 
> iot litearly took me  6mintues
> 

Time well spent 👍

**Comment by shruuub** [comment]
Tho I do fail to set it up too 😄
